---
- name: deploy apache server
  hosts: webservers
  become: yes 
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: latest
  - name: Enable ans start httpd service
    service:
      name: httpd
      state: started
      enabled: true 
  - name: Create index.html file for hosting static content
    copy:
      content: "Hoorraayyy!!! My first playbook ran successfullty"
      dest: /var/www/html/index.html
