---
- name: Install Apache and start the service
  hosts: webservers
  become: yes
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: python-httplib2
    rule: http
  tasks:
    - name: install packages
      yum:
        name:
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
          - "{{ python_pkg }}"

        state: latest

    - name: start the services httpd 
      service:
          name: "{{ web_service }}"
          state: started
          enabled: true
            
    - name: start the services firewalld
      service:
          name: "{{ firewall_service }}"
          state: started
          enabled: true

    - name: add content to the web page
      copy:
        content: "Example web content\n"
        dest: /var/www/html/index.html
    - name:  add http port to firewall
      firewalld: 
        service: http
        immediate: yes
        permanent: yes
        state: enabled
