---
- name: install "{{ package }}"
  yum:
    name: "{{ package }}"
    state: latest
- name: start "{{ service }}"
  service:
    name: "{{ service }}"
    state: "{{ svc_state }}"
    enabled: true
